### ISSUE TITLE
".nobackup" support

### ISSUE THREAD

**Issue by prof-milki** [malessandrini/prebackup#1]
Hi,

Just noticed your project on [freshcode](http://freshcode.club/projects/prebackup). And well, like everyone, I'm also somewhat overdue with crafting a recent backup.

Anyway, this is a far-fetched feature request:
 - I've started to tag some directories with "**.nobackup**" files years ago.
 - Similar to your `_nobackup_` - except that it's a *hidden* file. Slightly less visible and such.
 - Made it just as easy to build exclusion lists.
      - (always used it just via `find` to exclude whole dirs)
      - (better yet would be allowing relative placeholders/greps in there though...?)
 - Could the exact basename of that *nobackup tagfile be configurable?

(Also. Yes, should have read your docs more closely. You already alluded to possible placeholders in there.)

Obviously neither *nobackup name is a widespread standard or anything. Very obviously more than one person came up and reinvented the same idea still ;)
 - Just read something like this it on Slashdot or so (way back).
 - Presumably there might be a more common name for this already.
 - Someone more inclined might/would want to organize a get-together/mini-mailing-list for backup tool developers (rsync, bacula, kbackup, BIT, etc) to come up with some form of proper default for such a thing....

Sorry, Just my 5 minutes on random far-fetched feature requests ;)

**Comment by malessandrini** [comment]
Hi, thank you for your interest! I wrote the entry on freshcode just yesterday, because I made the program for myself, but I think it could be useful to others, too.

You're absolutely right about the "nobackup" tag, I just invented it but it's not a very good name. Something like an hidden file would be better. Anyway I did not find a common "standard" on Internet. What would be better in my opinion too, is making it configurable. In the next days I want to add that feature, I already planned it. I'll write here when it's done.

About the other suggestions, I don't fully understand, can you elaborate more? There's an option to create an exclusion file for backup programs not supporting excluding dirs with tagging files. Consider that this is not a real backup program, so I'd like to keep it simple and not add complex features already implemented in actual backup programs. For example, some programs can exclude cache directories (of browsers, etc) by looking at certain tags. In this case the worst it can happen is that Prebackup would overestimate the total size a little.

Ah, a common place to discuss backups would be wonderful, there's not much organized places like that.

Bye and thanks for your suggestions, don't be afraid of elaborating more, I'm happy to see I could have made something useful

Michele

**Comment by malessandrini** [comment]
Hi, I implemented the configurable exclusion tag (I could not wait :-) ). I set the default name to `.nobackup`.

I pushed to the repository and added a 1.1 release. Would you give it a test?

Bye
Michele
